name: Linter
on: [ push, pull_request ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "project"
        strict: "low"
        mypy-options: "--ignore-missing-imports --show-error-codes"
        isort-options: "-w 120"
        black-options: "-l 120 --diff"
